# jetson/config.yml

network:
  raspberry_pi_ip: "192.168.1.100"
  jetson_ip: "192.168.1.101"
  
  mcp_server:
    host: "192.168.1.100"
    port: 8080
    ws_port: 8081
  
  mqtt_broker:
    host: "192.168.1.100"
    port: 1883
  
  n8n_server:
    host: "192.168.1.100"
    port: 5678

agent:
  id: "jetson-conversational-01"
  type: "conversational"
  name: "Agent Conversationnel Principal"

modules:
  vision:
    enabled: true
    camera:
      type: "csi"  # ou "usb"
      device: 0
      width: 1920
      height: 1080
      fps: 30
    yolo:
      model: "models/yolo11n.engine"
      conf_threshold: 0.5
      iou_threshold: 0.45
    face_recognition:
      model: "buffalo_l"
      threshold: 0.6
      embeddings_file: "models/face_embeddings.pkl"
  
  audio:
    enabled: true
    stt:
      engine: "whisper"  # whisper ou vosk
      model: "models/whisper-medium.bin"
      language: "fr"
    tts:
      engine: "piper"  # piper ou espeak
      model: "fr_FR-siwis-medium"
      rate: 1.0
    microphone:
      device: "default"
      sample_rate: 16000
      channels: 1
    speaker:
      device: "pulse"  # Pour Bluetooth
  
  llm:
    enabled: true
    engine: "ollama"  # ← NOUVEAU : ollama au lieu de llama.cpp
    
    ollama:
      host: "localhost"
      port: 11434
      model: "llama3.1:8b"  # Modèle par défaut
      
      # Modèles disponibles (à télécharger)
      available_models:
        - "llama3.1:8b"      # Recommandé - Équilibré
        - "mistral:7b"       # Rapide et efficace
        - "phi3:medium"      # Ultra-léger (3.8B)
        - "gemma2:9b"        # Google, très bon
        - "qwen2.5:7b"       # Multilingue excellent
      
      # Paramètres génération
      temperature: 0.7
      top_p: 0.9
      top_k: 40
      num_ctx: 8192        # Taille contexte
      num_gpu: 1           # Utiliser GPU
      num_thread: 4
      repeat_penalty: 1.1
    
    # API server pour n8n
    api_server:
      enabled: true
      port: 8001
      format: "openai"  # Compatible OpenAI API

logging:
  level: "INFO"
  file: "logs/agent.log"
  max_size_mb: 100
  backup_count: 5

performance:
  vision_fps_target: 15
  audio_chunk_duration_ms: 1000